export const SEED_EXPERIENCE = [
  {
    slug: 'notz-ltda-fullstack-developer',
    role: 'Desenvolvedor Full Stack',
    company: 'Notz LTDA',
    description:
      'Atuação no desenvolvimento e manutenção de soluções web, automações e integrações, com foco em backend, produto e operação de sistemas em produção.',
    location: 'Remoto',
    employmentType: 'PJ',
    startDate: '2021-07-01',
    endDate: null,
    isCurrent: true,
    order: 0,
    status: 'published' as const,
    logoUrl: null,
    credentialUrl: null,
    impactFacts: [
      'Único dev responsável pela stack: backend, frontend, integrações, infra, deploy e operação.',
      'Processamento assíncrono com BullMQ + Redis: retry exponencial, DLQ, expiração e reembolso automático.',
      'Observabilidade e segurança com OpenTelemetry, JWT HTTP-only, rate limit Redis, CSRF e sanitização.',
      'Entrega de funcionalidades completas com documentação técnica, testes Vitest e pipeline CI/CD.',
    ],
    skillSlugs: [
      'typescript',
      'javascript',
      'nodejs',
      'php',
      'postgresql',
      'mongodb',
      'redis',
      'react',
      'nextjs',
      'docker',
      'docker-compose',
      'bun',
      'hono',
      'bullmq',
      'drizzle',
      'vitest',
      'opentelemetry',
      'git',
      'github',
      'vps',
    ],
  },
];

export const SEED_EDUCATION = [
  {
    slug: 'engenharia-de-software-cruzeiro-do-sul',
    title: 'Engenharia de Software',
    institution: 'Universidade Cruzeiro do Sul',
    description: 'Graduação bacharelado em Engenharia de Software, modalidade EAD.',
    location: 'EAD',
    educationType: 'Graduação - Bacharel',
    startDate: '2025-08-01',
    endDate: null,
    isCurrent: true,
    workloadHours: null,
    credentialId: null,
    credentialUrl: null,
    order: 0,
    status: 'published' as const,
    logoUrl: null,
  },
  {
    slug: 'google-cloud-computing-foundations-certificate',
    title: 'Google Cloud Computing Foundations Certificate',
    institution: 'Google',
    description: 'Curso remoto de fundamentos de cloud computing com carga horária de 50 horas.',
    location: 'Remoto',
    educationType: 'Curso',
    startDate: null,
    endDate: null,
    isCurrent: false,
    workloadHours: 50,
    credentialId: null,
    credentialUrl: null,
    order: 1,
    status: 'published' as const,
    logoUrl: null,
  },
];
