import { resolveTagIcon } from '@portfolio/shared/lib/iconResolver';

const _RAW_SEED_TAGS = [
  { name: 'TypeScript', slug: 'typescript', category: 'language' as const, isHighlighted: true },
  { name: 'JavaScript', slug: 'javascript', category: 'language' as const, isHighlighted: true },
  { name: 'Node.js', slug: 'nodejs', category: 'tool' as const, isHighlighted: true },
  { name: 'React', slug: 'react', category: 'framework' as const, isHighlighted: true },
  { name: 'Next.js', slug: 'nextjs', category: 'framework' as const, isHighlighted: true },
  { name: 'Hono', slug: 'hono', category: 'framework' as const, isHighlighted: true },
  { name: 'Elysia', slug: 'elysia', category: 'framework' as const, isHighlighted: false },
  {
    name: 'TanStack Start',
    slug: 'tanstack-start',
    category: 'framework' as const,
    isHighlighted: false,
  },
  { name: 'Tailwind CSS', slug: 'tailwind', category: 'framework' as const, isHighlighted: false },
  { name: 'PostgreSQL', slug: 'postgresql', category: 'db' as const, isHighlighted: true },
  { name: 'Redis', slug: 'redis', category: 'db' as const, isHighlighted: true },
  { name: 'MongoDB', slug: 'mongodb', category: 'db' as const, isHighlighted: false },
  { name: 'Docker', slug: 'docker', category: 'infra' as const, isHighlighted: true },
  {
    name: 'Docker Compose',
    slug: 'docker-compose',
    category: 'infra' as const,
    isHighlighted: false,
  },
  { name: 'Bun', slug: 'bun', category: 'tool' as const, isHighlighted: true },
  { name: 'Drizzle ORM', slug: 'drizzle', category: 'tool' as const, isHighlighted: true },
  { name: 'Vitest', slug: 'vitest', category: 'tool' as const, isHighlighted: false },
  { name: 'BullMQ', slug: 'bullmq', category: 'tool' as const, isHighlighted: true },
  { name: 'Git', slug: 'git', category: 'tool' as const, isHighlighted: false },
  { name: 'GitHub', slug: 'github', category: 'tool' as const, isHighlighted: false },
  {
    name: 'GitHub Actions',
    slug: 'github-actions',
    category: 'infra' as const,
    isHighlighted: false,
  },
  { name: 'VPS', slug: 'vps', category: 'infra' as const, isHighlighted: false },
  {
    name: 'OpenTelemetry',
    slug: 'opentelemetry',
    category: 'infra' as const,
    isHighlighted: false,
  },
  { name: 'OpenAPI', slug: 'openapi', category: 'tool' as const, isHighlighted: false },
  {
    name: 'Feature Flags',
    slug: 'feature-flags',
    category: 'other' as const,
    isHighlighted: false,
  },
  {
    name: 'Entrega Contínua',
    slug: 'continuous-delivery',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Rollback', slug: 'rollback', category: 'other' as const, isHighlighted: false },
  {
    name: 'Débito Técnico',
    slug: 'technical-debt',
    category: 'other' as const,
    isHighlighted: false,
  },
  {
    name: 'Álgebra Booleana',
    slug: 'boolean-algebra',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Clean Code', slug: 'clean-code', category: 'other' as const, isHighlighted: false },
  {
    name: 'Regras de Negócio',
    slug: 'business-rules',
    category: 'other' as const,
    isHighlighted: false,
  },
  {
    name: 'Cache Stampede',
    slug: 'cache-stampede',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Arquitetura', slug: 'architecture', category: 'other' as const, isHighlighted: false },
  {
    name: 'System Design',
    slug: 'system-design',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'IEEE 754', slug: 'ieee-754', category: 'other' as const, isHighlighted: false },
  {
    name: 'Sistemas Financeiros',
    slug: 'financial-systems',
    category: 'other' as const,
    isHighlighted: false,
  },
  {
    name: 'Tratamento de Erros',
    slug: 'error-handling',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Filas', slug: 'queues', category: 'other' as const, isHighlighted: false },
  {
    name: 'Fila de Mensagens',
    slug: 'message-queue',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Backend', slug: 'backend', category: 'other' as const, isHighlighted: false },
  {
    name: 'Observabilidade',
    slug: 'observabilidade',
    category: 'other' as const,
    isHighlighted: false,
  },
  { name: 'Idempotência', slug: 'idempotencia', category: 'other' as const, isHighlighted: false },
  {
    name: 'Ponto Flutuante',
    slug: 'ponto-flutuante',
    category: 'other' as const,
    isHighlighted: false,
  },
  {
    name: 'Padrão Outbox',
    slug: 'padrao-outbox',
    category: 'other' as const,
    isHighlighted: false,
  },
];

export const SEED_TAGS = _RAW_SEED_TAGS.map((seedTag) => ({
  ...seedTag,
  iconKey: resolveTagIcon(seedTag.name, seedTag.category).iconKey,
}));

const _RAW_SEED_SKILLS = [
  {
    name: 'TypeScript',
    slug: 'typescript',
    category: 'language' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'JavaScript',
    slug: 'javascript',
    category: 'language' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'PHP',
    slug: 'php',
    category: 'language' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Hono',
    slug: 'hono',
    category: 'framework' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'Next.js',
    slug: 'nextjs',
    category: 'framework' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'React',
    slug: 'react',
    category: 'framework' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Tailwind CSS',
    slug: 'tailwind',
    category: 'framework' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Elysia',
    slug: 'elysia',
    category: 'framework' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'TanStack Start',
    slug: 'tanstack-start',
    category: 'framework' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Zod',
    slug: 'zod',
    category: 'framework' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'shadcn/ui',
    slug: 'shadcn-ui',
    category: 'framework' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'grammY',
    slug: 'grammy',
    category: 'framework' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Bun',
    slug: 'bun',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'Drizzle ORM',
    slug: 'drizzle',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'Node.js',
    slug: 'nodejs',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'BullMQ',
    slug: 'bullmq',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Vitest',
    slug: 'vitest',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Playwright',
    slug: 'playwright',
    category: 'tool' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Biome',
    slug: 'biome',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'OpenAPI',
    slug: 'openapi',
    category: 'tool' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Git',
    slug: 'git',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'GitHub',
    slug: 'github',
    category: 'tool' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'PostgreSQL',
    slug: 'postgresql',
    category: 'db' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'Redis',
    slug: 'redis',
    category: 'db' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    category: 'db' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Docker',
    slug: 'docker',
    category: 'infra' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'GitHub Actions',
    slug: 'github-actions',
    category: 'infra' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 1 as const,
  },
  {
    name: 'Docker Compose',
    slug: 'docker-compose',
    category: 'infra' as const,
    expertiseLevel: 3 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'OpenTelemetry',
    slug: 'opentelemetry',
    category: 'infra' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Traefik',
    slug: 'traefik',
    category: 'infra' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'Grafana',
    slug: 'grafana',
    category: 'infra' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'VPS',
    slug: 'vps',
    category: 'infra' as const,
    expertiseLevel: 2 as const,
    isHighlighted: 0 as const,
  },
  {
    name: 'GCP',
    slug: 'gcp',
    category: 'cloud' as const,
    expertiseLevel: 1 as const,
    isHighlighted: 0 as const,
  },
];

export const SEED_SKILLS = _RAW_SEED_SKILLS.map((seedSkill) => ({
  ...seedSkill,
  iconKey: resolveTagIcon(seedSkill.name, seedSkill.category).iconKey,
}));
